# Generated by Django 3.0.3 on 2020-04-23 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='room_db',
            fields=[
                ('room_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='request_db',
            fields=[
                ('request_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('slot', models.CharField(choices=[('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200, null=True)),
                ('authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pgi_app.room_db')),
            ],
        ),
        migrations.CreateModel(
            name='authority_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('Club secretary', 'Club secretary'), ('Club Office In-charge', 'Club Office In-charge'), ('Security In-charge', 'Security In-charge'), ('Guard In-charge', 'Guard In-charge')], max_length=200, null=True)),
                ('club', models.CharField(choices=[('Club 1', 'Club 1'), ('Club 2', 'Club 2'), ('Club 3', 'Club 3'), ('Club 4', 'Club 4'), ('NA', 'NA')], max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
