# Generated by Django 3.0.3 on 2020-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0002_auto_20200423_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_db',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
