# Generated by Django 3.0.3 on 2020-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0005_auto_20200423_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_db',
            name='room_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room_db',
            name='room_number',
            field=models.CharField(max_length=200),
        ),
    ]
