# Generated by Django 3.0.3 on 2020-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0007_auto_20200423_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_db',
            name='room_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
