# Generated by Django 3.0.3 on 2020-04-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0008_auto_20200423_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_db',
            name='room_id',
        ),
        migrations.AlterField(
            model_name='room_db',
            name='room_number',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
