# Generated by Django 3.0.3 on 2020-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0009_auto_20200423_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_db',
            name='status',
            field=models.CharField(choices=[('-1', '-1'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200, null=True),
        ),
    ]
