# Generated by Django 3.0.3 on 2020-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0010_auto_20200425_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority_db',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
