# Generated by Django 3.0.3 on 2020-04-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0011_authority_db_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority_db',
            name='profile_pic',
        ),
    ]
