# Generated by Django 3.0.3 on 2020-04-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0013_authority_db_ub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority_db',
            name='ub',
        ),
    ]
