# Generated by Django 3.0.3 on 2020-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0015_authority_db_ub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority_db',
            name='ub',
            field=models.CharField(default='', max_length=200),
        ),
    ]
