# Generated by Django 3.0.3 on 2020-04-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0018_auto_20200429_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authority_db',
            name='ub',
        ),
    ]
