# Generated by Django 3.0.5 on 2020-04-29 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgi_app', '0020_pic_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_db',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
