# Generated by Django 3.0.5 on 2020-04-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_app', '0021_auto_20200429_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pic_db',
        ),
    ]
